const colorTable=[
    {
        color:'#fff',
        background:'#1abc9c'
    },
    {
        color:'#fff',
        background:'#2ecc71'
    }
    ,
    {
        color:'#fff',
        background:'#3498db'
    }
    ,
    {
        color:'#fff',
        background:'#9b59b6'
    },
    {
        color:'#fff',
        background:'#34495e'
    }
    ,
    {
        color:'#fff',
        background:'#f1c40f'
    }
    ,
    {
        color:'#fff',
        background:'#e67e22'
    }
    ,
    {
        color:'#fff',
        background:'#e74c3c'
    }
    ,
    {
        color:'#fff',
        background:'#95a5a6'
    }
    ,
    {
        color:'#fff',
        background:'#f39c12'
    }
    ,
    {
        color:'#fff',
        background:'#d35400'
    }
    ,
    {
        color:'#fff',
        background:'#c0392b'
    }
    ,
    {
        color:'#fff',
        background:'#bdc3c7'
    }
    ,
    {
        color:'#fff',
        background:'#7f8c8d'
    }
    ,
    {
        color:'#fff',
        background:'#55efc4'
    }
    ,
    {
        color:'#fff',
        background:'#81ecec'
    }
    ,
    {
        color:'#fff',
        background:'#74b9ff'
    }
    ,
    {
        color:'#fff',
        background:'#a29bfe'
    }
    ,
    {
        color:'#fff',
        background:'#00b894'
    }
    ,
    {
        color:'#fff',
        background:'#00cec9'
    }
    ,
    {
        color:'#fff',
        background:'#0984e3'
    }
    ,
    {
        color:'#fff',
        background:'#6c5ce7'
    }
    ,
    {
        color:'#fff',
        background:'#b2bec3'
    }
    ,
    {
        color:'#fff',
        background:'#ffeaa7'
    }
    ,
    {
        color:'#fff',
        background:'#fab1a0'
    }
    ,
    {
        color:'#fff',
        background:'#ff7675'
    }
    ,
    {
        color:'#fff',
        background:'#fd79a8'
    }
    ,
    {
        color:'#fff',
        background:'#636e72'
    }
    ,
    {
        color:'#fff',
        background:'#fdcb6e'
    }
    ,
    {
        color:'#fff',
        background:'#e17055'
    }
    ,
    {
        color:'#fff',
        background:'#ff7675'
    }
    ,
    {
        color:'#fff',
        background:'#fd79a8'
    }
    ,
    {
        color:'#fff',
        background:'#636e72'
    }
    ,
    {
        color:'#fff',
        background:'#fdcb6e'
    }
    ,
    {
        color:'#fff',
        background:'#e17055'
    }
    ,
    {
        color:'#fff',
        background:'#d63031'
    }
    ,
    {
        color:'#fff',
        background:'#e84393'
    }
    ,
    {
        color:'#fff',
        background:'#2d3436'
    }
    ,
    {
        color:'#fff',
        background:'#ef5777'
    }
    ,
    {
        color:'#fff',
        background:'#ff3f34'
    }
    ,
    {
        color:'#fff',
        background:'#1e272e'
    }
    ,
    {
        color:'#fff',
        background:'#05c46b'
    }
    ,
    {
        color:'#fff',
        background:'#3c40c6'
    }
]

export function getColor(str){
    str = str||'a'
    let colorIndex = str.charCodeAt(0) % colorTable.length
    return colorTable[colorIndex]
}