export const CREATE_VIEW_DATA = "__createViewData__"
export const LIST_VIEW_DATA = "__listViewData__"
export const DETAIL_VIEW_DATA = "__detailViewData__"
export const EDIT_VIEW_DATA = "__editViewData__"
export const RECORD_TAG = "__tag__"
export const ARGS = '__args__'
export const VIEW_COMMON_FIELDS_TAB_KEY="__view_common_fields_tab_key"
export const VIEW_COMMON_FIELDS_TAB_TITLE="通用信息"
export const MODEL_FIELD_UPDATE_FLAG = "__modelFieldUpdateFlag__"